# Generated by Django 6.1.1 on 2026-09-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                ("opis_id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("retail_price", models.DecimalField(decimal_places=8, max_digits=12)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("coordinate_source", models.CharField(blank=True, max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retail_price__gt", 0)), name="positive_station_price"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                            models.Q(("latitude__range", (-90, 90)), ("longitude__range", (-180, 180))),
                            _connector="OR",
                        ),
                        name="valid_coordinate_pair",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("rack_id", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=8, max_digits=12)),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("source_row", models.JSONField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="routes.fuelstation",
                    ),
                ),
            ],
        ),
    ]
