# Generated by Django 6.1.1 on 2026-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fuelstation",
            name="valid_coordinate_pair",
        ),
        migrations.AddConstraint(
            model_name="fuelstation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(
                        ("latitude__isnull", False),
                        ("latitude__range", (-90, 90)),
                        ("longitude__isnull", False),
                        ("longitude__range", (-180, 180)),
                    ),
                    _connector="OR",
                ),
                name="valid_coordinate_pair",
            ),
        ),
    ]
